[workspace]
members = [
    "polytool",
    "polytool/web",
    "polytool/mcp",
    "combinatoric-core",
    "combpoly",
    "flagged-lorentzian",
    "polynomial-lab",
    "polynomial-lab/mcp",
    "sym-poly/core",
    "sym-poly/sym",
    "sym-poly/qsym",
    "sym-poly/multipoly",
]
exclude = ["experiments", "KTT-search", "kostka"]
default-members = [
    "polytool",
    "polytool/web",
    "polytool/mcp",
    "combinatoric-core",
    "combpoly",
    "flagged-lorentzian",
    "polynomial-lab",
    "polynomial-lab/mcp",
    "sym-poly/core",
    "sym-poly/sym",
    "sym-poly/qsym",
    "sym-poly/multipoly",
]
resolver = "2"
